### ISSUE TITLE
lremove missing

### ISSUE THREAD

**Issue by effelsberg** [auriocus/ukaz#1]
lremove does not yet exist in Tcl 8.6, perhaps in 8.7.

Ad hoc version in Suchenwirth style:

proc lremove {list what } {
    return [lsearch -all -inline -not -exact $list $what]
}

**Comment by auriocus** [comment]
On 04.08.2015 11:59, Stephan Effelsberg wrote:

> lremove does not yet exist in Tcl 8.6, perhaps in 8.7.

sorry for this. tkcon defines a more elaborate version. Since I'm doing 
all testing within tkcon, that was not noticed.

> Ad hoc version in Suchenwirth style:
> 
> proc lremove {list what } {
> return [lsearch -all -inline -not -exact $list $what]
> }

Will be fixed soon.

**Comment by auriocus** [comment]
Fixed in the suggested way
